### ISSUE TITLE
updagre apoc to 4.4

### ISSUE THREAD

**Issue by AaronYang2333** [michael-simons/neo4j-examples-and-tips#6]
Hi Michael,
Thanks for sharing this useful repo and clear code for all, and I am able to use APOC in embedded Neo4j to do some business. But I noticed there is already a newer version of APOC listed on the maven central repo. When I tried to use the following code and a newer version of APOC, it would have a compile error. And the important ApocConfig.class is missing. so could you have any suggestion to solve it? Thanks in advance.

```java
private static Neo4j neo4j;

	@BeforeAll
	static void startEmbeddedNeo4j() throws URISyntaxException {

		// We need the directory containing the APOC jar, otherwise all APOC procedures must be loaded manually.
		// While the intuitive idea might be not having APOC on the class path at all in that case and just dump
		// it into the plugin directory, it doesn't work as APOC needs some extension factories to work with
		// and those are not loaded from the plugin unless it's part of the original class loader that loaded neo.
		// If you know which methods you're a gonna use, you can configure them manually instead.
		var pluginDirContainingApocJar = new File(
			ApocConfig.class.getProtectionDomain().getCodeSource().getLocation().toURI())
			.getParentFile().toPath();
		neo4j = Neo4jBuilders
			.newInProcessBuilder()
			.withDisabledServer() // We don't need the HTTP endpoint
			.withFixture("CREATE (m:Movie {title: 'Fight Club'}) RETURN m")
			.withConfig(GraphDatabaseSettings.plugin_dir, pluginDirContainingApocJar)
			.withConfig(GraphDatabaseSettings.procedure_unrestricted, List.of("apoc.*"))
			.build();

	}
```

the newer version of APOC I used is
```xml
<!-- https://mvnrepository.com/artifact/org.neo4j.procedure/apoc -->
<dependency>
    <groupId>org.neo4j.procedure</groupId>
    <artifactId>apoc</artifactId>
    <version>4.4.0.9</version>
</dependency>

```
and I also tried to upgrade the Neo4j version, but it doesn't work.

**Comment by michael-simons** [comment]
Hej @AaronYang2333 for whatever reason I missed this issue. Sorry for that.

The basic idea is: You need to pick any class in the apoc package, to get to the protection domain and eventually the code sources. Doesn't matter which, as long as it is in the apoc jar you wanna use.

However, I already raised an issue with the team: Everything APOC >= 4.1.0.0 and < 5 seems to be broken and not usable as dependency in that way,

**Comment by michael-simons** [comment]
Hah, it was a me error.

So, you need to include the full distribution, qualified as `all`

```
	<dependency>
			<groupId>org.neo4j.procedure</groupId>
			<artifactId>apoc</artifactId>
			<version>4.4.0.9</version>
			<scope>test</scope>
			<classifier>all</classifier>
		</dependency>
```

And for safety, I changed the test code a bit.

The reason here is that apoc has been split into core and extended. Core is distributed with Neo4j 5+ (and I think in parts with some 4x distributions too).
That is ofc not the case in the embedded distribution, as it is not part of the dependencies.
